### ISSUE TITLE
first run is succesful, second run crashes

### ISSUE THREAD

**Issue by xx88xx** [Seedsa/Fooocus_Nodes#18]
Here is the terminal logs:

[AnimateDiffEvo] - INFO - Sliding context window activated - latents passed in (128) greater than context_length 16.
[AnimateDiffEvo] - INFO - Using motion module mm-Stabilized_high.pth:v1.
 17%|█▋        | 3/18 [03:05<15:27, 61.84s/it]got prompt
172.17.0.1 - - [28/May/2024 03:30:47] "GET /assets/index-BcHurkhF.css HTTP/1.1" 304 -
172.17.0.1 - - [28/May/2024 03:30:48] "GET /assets/index-B7I_54js.js HTTP/1.1" 200 -
172.17.0.1 - - [28/May/2024 03:30:49] "GET /api/settings HTTP/1.1" 200 -
172.17.0.1 - - [28/May/2024 03:31:41] "GET / HTTP/1.1" 200 -
172.17.0.1 - - [28/May/2024 03:31:42] "GET /assets/index-BcHurkhF.css HTTP/1.1" 304 -
172.17.0.1 - - [28/May/2024 03:31:42] "GET /assets/index-B7I_54js.js HTTP/1.1" 304 -
172.17.0.1 - - [28/May/2024 03:31:42] "GET /api/settings HTTP/1.1" 200 -
172.17.0.1 - - [28/May/2024 03:31:42] "GET /api/projects HTTP/1.1" 200 -
172.17.0.1 - - [28/May/2024 03:31:53] "GET /api/projects HTTP/1.1" 200 -
 39%|███▉      | 7/18 [07:15<11:26, 62.39s/it]/app/server/projects/stop-wars/comfyui/web/comfyui_index.html
FETCH DATA from: /app/server/projects/stop-wars/comfyui/custom_nodes/ComfyUI-Manager/extension-node-map.json [DONE]
FETCH DATA from: /app/server/projects/stop-wars/comfyui/custom_nodes/ComfyUI-Manager/extension-node-map.json [DONE]
[ERROR] An error occurred while retrieving information for the 'Fooocus ultralyticsDetectorPipe' node.
Traceback (most recent call last):
  File "/app/server/projects/stop-wars/comfyui/server.py", line 415, in get_object_info
    out[x] = node_info(x)
  File "/app/server/projects/stop-wars/comfyui/server.py", line 393, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/app/server/projects/stop-wars/comfyui/custom_nodes/Fooocus_Nodes/py/fooocusNodes.py", line 1368, in INPUT_TYPES
    bboxs = ["bbox/" + x for x in folder_paths.get_filename_list("ultralytics_bbox")]
  File "/app/server/projects/stop-wars/comfyui/folder_paths.py", line 225, in get_filename_list
    out = get_filename_list_(folder_name)
  File "/app/server/projects/stop-wars/comfyui/folder_paths.py", line 192, in get_filename_list_
    folders = folder_names_and_paths[folder_name]
KeyError: 'ultralytics_bbox'

[ERROR] An error occurred while retrieving information for the 'Fooocus samLoaderPipe' node.
Traceback (most recent call last):
  File "/app/server/projects/stop-wars/comfyui/server.py", line 415, in get_object_info
    out[x] = node_info(x)
  File "/app/server/projects/stop-wars/comfyui/server.py", line 393, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/app/server/projects/stop-wars/comfyui/custom_nodes/Fooocus_Nodes/py/fooocusNodes.py", line 1398, in INPUT_TYPES
    "model_name": (folder_paths.get_filename_list("sams"),),
  File "/app/server/projects/stop-wars/comfyui/folder_paths.py", line 225, in get_filename_list
    out = get_filename_list_(folder_name)
  File "/app/server/projects/stop-wars/comfyui/folder_paths.py", line 192, in get_filename_list_
    folders = folder_names_and_paths[folder_name]
KeyError: 'sams'

172.17.0.1 - - [28/May/2024 03:32:10] "GET /api/settings HTTP/1.1" 200 -
172.17.0.1 - - [28/May/2024 03:32:10] "GET /api/projects HTTP/1.1" 200 -
 56%|█████▌    | 10/18 [10:23<08:19, 62.42s/it]got prompt
172.17.0.1 - - [28/May/2024 03:38:18] "GET /api/settings HTTP/1.1" 200 -
172.17.0.1 - - [28/May/2024 03:38:18] "GET /api/projects HTTP/1.1" 200 -
172.17.0.1 - - [28/May/2024 03:38:23] "POST /api/projects/stop-wars/stop HTTP/1.1" 200 -
172.17.0.1 - - [28/May/2024 03:38:23] "GET /api/projects HTTP/1.1" 200 -
 72%|███████▏  | 13/18 [13:30<05:12, 62.49s/it]172.17.0.1 - - [28/May/2024 03:38:33] "GET /api/projects HTTP/1.1" 200 -

**Comment by xx88xx** [comment]
> you need to install 'Impact Pack' first

this seems to have fixed it! thank you!
