### ISSUE TITLE
Last update make erros and not run

### ISSUE THREAD

**Issue by MattRM2** [Seedsa/Fooocus_Nodes#24]
Hi @Seedsa ,

Since I got the last update today, I got this error : 
`[Fooocus] Initializing ...
[Fooocus] Loading models ...
!!! Exception during processing!!! E:\00_ComfyUI_Fooocus\ComfyUI\models\fooocus_expansion does not appear to have a file named config.json. Checkout 'https://huggingface.co/E:\00_ComfyUI_Fooocus\ComfyUI\models\fooocus_expansion/tree/None' for available files.
Traceback (most recent call last):
  File "E:\00_ComfyUI_Fooocus\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\00_ComfyUI_Fooocus\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\00_ComfyUI_Fooocus\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\00_ComfyUI_Fooocus\ComfyUI\custom_nodes\Fooocus_Nodes\py\fooocusNodes.py", line 423, in fooocus_preKSampler
    pipeline.refresh_everything(
  File "E:\00_ComfyUI_Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\00_ComfyUI_Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\00_ComfyUI_Fooocus\ComfyUI\custom_nodes\Fooocus_Nodes\py\modules\default_pipeline.py", line 247, in refresh_everything
    final_expansion = FooocusExpansion()
  File "E:\00_ComfyUI_Fooocus\ComfyUI\custom_nodes\Fooocus_Nodes\py\extras\expansion.py", line 39, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(path_fooocus_expansion)
  File "E:\00_ComfyUI_Fooocus\python_embeded\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 837, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "E:\00_ComfyUI_Fooocus\python_embeded\lib\site-packages\transformers\models\auto\configuration_auto.py", line 934, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "E:\00_ComfyUI_Fooocus\python_embeded\lib\site-packages\transformers\configuration_utils.py", line 632, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "E:\00_ComfyUI_Fooocus\python_embeded\lib\site-packages\transformers\configuration_utils.py", line 689, in _get_config_dict
    resolved_config_file = cached_file(
  File "E:\00_ComfyUI_Fooocus\python_embeded\lib\site-packages\transformers\utils\hub.py", line 370, in cached_file
    raise EnvironmentError(
OSError: E:\00_ComfyUI_Fooocus\ComfyUI\models\fooocus_expansion does not appear to have a file named config.json. Checkout 'https://huggingface.co/E:\00_ComfyUI_Fooocus\ComfyUI\models\fooocus_expansion/tree/None' for available files.

Prompt executed in 4.77 seconds
`
The file is present in the folder : 
![image](https://github.com/Seedsa/Fooocus_Nodes/assets/25594057/415ae4f1-453a-44f5-aeae-812e3a284d4c)

What I can do to fix this ?
Thanks,

In between, I'll roll back

Matt

**Comment by Seedsa** [comment]
Fixed now.

**Comment by MattRM2** [comment]
> Fixed now.

Hi,

Thank you very much !!!
Have a nice day !!!

Matt
