### ISSUE TITLE
something's wrong with node paths

### ISSUE THREAD

**Issue by TorAllex** [Seedsa/Fooocus_Nodes#28]
```
[ERROR] An error occurred while retrieving information for the 'Fooocus ultralyticsDetectorPipe' node.
Traceback (most recent call last):
  File "/Users/alex/ComfyUI/server.py", line 434, in get_object_info
    out[x] = node_info(x)
  File "/Users/alex/ComfyUI/server.py", line 412, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/Users/alex/ComfyUI/custom_nodes/Fooocus_Nodes/py/fooocusNodes.py", line 1376, in INPUT_TYPES
    bboxs = ["bbox/" + x for x in folder_paths.get_filename_list("ultralytics_bbox")]
  File "/Users/alex/ComfyUI/folder_paths.py", line 228, in get_filename_list
    out = get_filename_list_(folder_name)
  File "/Users/alex/ComfyUI/folder_paths.py", line 195, in get_filename_list_
    folders = folder_names_and_paths[folder_name]
KeyError: 'ultralytics_bbox'

[ERROR] An error occurred while retrieving information for the 'Fooocus samLoaderPipe' node.
Traceback (most recent call last):
  File "/Users/alex/ComfyUI/server.py", line 434, in get_object_info
    out[x] = node_info(x)
  File "/Users/alex/ComfyUI/server.py", line 412, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/Users/alex/ComfyUI/custom_nodes/Fooocus_Nodes/py/fooocusNodes.py", line 1406, in INPUT_TYPES
    "model_name": (folder_paths.get_filename_list("sams"),),
  File "/Users/alex/ComfyUI/folder_paths.py", line 228, in get_filename_list
    out = get_filename_list_(folder_name)
  File "/Users/alex/ComfyUI/folder_paths.py", line 195, in get_filename_list_
    folders = folder_names_and_paths[folder_name]
KeyError: 'sams'
```

**Comment by Seedsa** [comment]
install [ComfyUI-Impact-Pack](https://github.com/ltdrdata/ComfyUI-Impact-Pack.git)

**Comment by TorAllex** [comment]
Ok, but Fooocus Styles:
```
Error occurred when executing Fooocus Styles:

'select_styles'

File "/Users/alex/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/Users/alex/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/Users/alex/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/Users/alex/ComfyUI/custom_nodes/Fooocus_Nodes/py/prompt.py", line 51, in run
if prompt[my_unique_id]["inputs"]["select_styles"]:
```
