### ISSUE TITLE
ModuleNotFoundError: No module named 'modules.sdxl_styles'

### ISSUE THREAD

**Issue by formulake** [Seedsa/Fooocus_Nodes#41]
This suddenly happened:

```
Traceback (most recent call last):
  File "F:\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI\custom_nodes\Fooocus_Nodes\__init__.py", line 43, in <module>
    imported_module = importlib.import_module(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI\custom_nodes\Fooocus_Nodes\py\api.py", line 9, in <module>
    from modules.sdxl_styles import legal_style_names
ModuleNotFoundError: No module named 'modules.sdxl_styles'
```

**Comment by formulake** [comment]
I think this is some kind of cross-wiring that's happened with my installation so I'm closing this since I don't believe it's within the purview of the dev.

**Comment by dancemanUK** [comment]
> 这突然发生了：
> 
> ```
> Traceback (most recent call last):
>   File "F:\ComfyUI\nodes.py", line 1993, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "F:\ComfyUI\custom_nodes\Fooocus_Nodes\__init__.py", line 43, in <module>
>     imported_module = importlib.import_module(
>                       ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "F:\ComfyUI\custom_nodes\Fooocus_Nodes\py\api.py", line 9, in <module>
>     from modules.sdxl_styles import legal_style_names
> ModuleNotFoundError: No module named 'modules.sdxl_styles'
> ```

me too ,same  ModuleNotFoundError: No module named 'modules.sdxl_styles'

**Comment by formulake** [comment]
I have different systems on which ComfyUI is installed and this wasn't happening on the others which is why I suspected that something had gone wrong with the dependencies. Unfortunately, I couldn't resolve the problem but a fresh installation worked just fine with all my original nodes reinstalled.
