### ISSUE TITLE
[ERROR] An error occurred while retrieving information for the 'Fooocus ultralyticsDetectorPipe' node.

### ISSUE THREAD

**Issue by klossm** [Seedsa/Fooocus_Nodes#43]
The following is the error message. How to fix it?The version of comfyui is the latest version

[ERROR] An error occurred while retrieving information for the 'Fooocus ultralyticsDetectorPipe' node.
Traceback (most recent call last):
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\server.py", line 552, in get_object_info
    out[x] = node_info(x)
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\server.py", line 520, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\Fooocus_Nodes\py\fooocusNodes.py", line 1393, in INPUT_TYPES
    bboxs = ["bbox/" + x for x in folder_paths.get_filename_list("ultralytics_bbox")]
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\folder_paths.py", line 270, in get_filename_list
    out = get_filename_list_(folder_name)
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\folder_paths.py", line 235, in get_filename_list_
    folders = folder_names_and_paths[folder_name]
KeyError: 'ultralytics_bbox'

[ERROR] An error occurred while retrieving information for the 'Fooocus samLoaderPipe' node.
Traceback (most recent call last):
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\server.py", line 552, in get_object_info
    out[x] = node_info(x)
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\server.py", line 520, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\Fooocus_Nodes\py\fooocusNodes.py", line 1423, in INPUT_TYPES
    "model_name": (folder_paths.get_filename_list("sams"),),
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\folder_paths.py", line 270, in get_filename_list
    out = get_filename_list_(folder_name)
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\folder_paths.py", line 235, in get_filename_list_
    folders = folder_names_and_paths[folder_name]
KeyError: 'sams'

**Comment by Seedsa** [comment]
install [ComfyUI-Impact-Pack](https://github.com/ltdrdata/ComfyUI-Impact-Pack.git).
